pipeline {
    agent any

    stages {
        stage('Login to Docker Hub') {
            steps {
                node{
                // Construir a imagem Docker
                    script {
                        withCredentials([usernamePassword( credentialsId: 'docker-login', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {

                            docker.withRegistry('', 'docker-login') {
                                sh "docker login -u ${USERNAME} -p ${PASSWORD}"
                                myImage.push("${env.BUILD_NUMBER}")
                                myImage.push("latest")
                            }
                        }
                    }
                }
            }
        }
        
        
        stage('Build') {
            steps {
                nodejs(nodeJSInstallationName: 'NodeInstalation') {
                    sh 'npm run test'
                    sh 'npm --version'
                }
            }
        }
    }
}
